---
abstract: 'Use the piwik API'
author:
  - 'Jens Gassmann <jegade@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Piwik-API
provides:
  Piwik::API:
    file: lib/Piwik/API.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
